name: Bug Report
description: Report a problem, issue or a bug.
title: "Minecraft Version: Issue Title"
labels: []
body:


- type: markdown
  attributes:
    value: |
      ### Please edit the issue title as follows:      

      Example:
      **Wrong title:** Chat event loses its format
      **Correct title:** 1.19.1: Chat event loses its format

      _Don't put "Paper" or "Spigot" etc. in your title._
      
- type: dropdown
  attributes:
    label: Are you using MySQL?
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true


- type: dropdown
  attributes:
    label: Are you using BungeeCord?
    description: |
      If you are using Velocity, use [this](https://github.com/kangarko/ChatControl-Red/issues/new?assignees=james090500&labels=velocity&template=bug_report_velocity.yml&title=Minecraft+Version%3A+Issue+Title) issue template instead.
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true

- type: input
  attributes:
    label: Error log (if applicable)
    description: If you are reporting a console error, upload any relevant log excerpts to either https://paste.gg or https://gist.github.com, save and the paste the link in this box.
    placeholder: "Paste link here"
  validations:
    required: false

- type: textarea
  attributes:
    label: '"/chc debug" output (strongly recommended)'
    description: |
      Run `/chc debug` in the console, then a debug ZIP file will be generated.
      
      **If you want to keep your settings private** Upload this ZIP file to [ufile.io](https://ufile.io) then email the link to support@mineacademy.org
      **Your database information from mysql.yml will be excluded.**
    placeholder: |
      Click here then drag the ZIP file here to upload it.
  validations:
    required: false


- type: textarea
  attributes:
    label: Information about the issue/bug
    description: How can we reproduce your issue?
  validations:
    required: true
