name: Question
description: Ask a question about the plugin.
title: "Minecraft Version: Your Question Title"
labels: []
body:


- type: markdown
  attributes:
    value: |
      ### Please edit the issue title as follows:
      
      Example:
      **Wrong title:** Chat event loses its format
      **Correct title:** 1.17.1: Chat event loses its format

      _Don't put "Paper" or "Spigot" etc. in your title._

- type: dropdown
  attributes:
    label: Are you using MySQL?
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true


- type: dropdown
  attributes:
    label: Are you using BungeeCord/Velocity?
    description: "This includes bungeecord forks like 'Waterfall' etc."
    options:
      - 'No'
      - 'Yes - BungeeCord'
      - 'Yes - Velocity'
  validations:
    required: true


- type: textarea
  attributes:
    label: Question
    description: Please be as a clear and concise as possible.
  validations:
    required: true
