name: Question
description: Ask a question about the plugin.
title: "Minecraft Version: Your Question Title"
labels: []
body:


- type: markdown
  attributes:
    value: |
      Hey there someone on the Internet!

      We're happy to help, because it's our mission. And we'd love to help you, too, so we ask you for a quick favor.
      Please read each section careful and answer each section accordingly
      
      ---

      ### Regarding Issue titles, edit them as shown below
      
      Example:
      **Wrong title:** Chat event loses its format
      **Correct title:** 1.17.1: Chat event loses its format

      _Don't put "Paper" or "Spigot" etc. in your title._
      
      ---


- type: input
  id: contact
  attributes:
    label: Minecraft Version
    description: |
      What version of minecraft is the server running on?
      If you are unsure, run the command ``/version`` to find out.
    placeholder: "1.18.2"
  validations:
    required: true


- type: dropdown
  attributes:
    label: Are you using MySQL?
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true


- type: dropdown
  attributes:
    label: Are you using BungeeCord?
    description: "This includes bungeecord forks like 'Waterfall' etc."
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true


- type: dropdown
  attributes:
    label: Are you using velocity?
    options:
      - 'No'
      - 'Yes'
  validations:
    required: true


- type: textarea
  attributes:
    label: Question
    description: Please be as a clear and concise as possible.
  validations:
    required: true
