name: Improvement
description: Suggest a new idea or a feature.
title: "Your Suggestion Title"
labels: []
body:

- type: markdown
  attributes:
    value: |
      Before making a new suggestion/feature request, please check that is hasn't already been added [here](https://github.com/kangarko/ChatControl-Red/issues/1)

- type: textarea
  attributes:
    label: "Summary"
    description: |
      Please enter a brief but clear and concise description of your suggestion/feature request or comments here.
  validations:
    required: false

- type: textarea
  attributes:
    label: "What would happen if we didn't implement this feature? Why not having this feature is a problem?"
    description: |
      Please be as a clear and concise as possible.
  validations:
    required: true
